name: 'turbo cache stuff lol'
description: 'do weird turbo things'
outputs:
  cache-url:
    description: "The cache URL"
    value: ${{ steps.outputs.outputs.cache-url }}
runs:
  using: "composite"
  steps:
    - name: Clone
      uses: actions/checkout@v4
      with:
        path: /tmp/turborepo-remote-cache
        repository: nora-heydecker-axa/turborepo-remote-cache
    - name: Start stuff
      run: |
        cd /tmp/turborepo-remote-cache
        pnpm install
        pnpm build
        nohup node dist/index.js &
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
        TURBO_TOKEN: meow
        TURBO_TEAM: cats
        STORAGE_PROVIDER: github-actions-cache

    - name: Set output
      id: outputs
      run: |
        echo "cache-url=http://localhost:3000" >> $GITHUB_OUTPUT
      shell: bash
